routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Route::get('/', function () {
    return view('welcome');
});*/


Auth::routes();

Route::get('/', 'IndexController@index');
Route::get('/entrar', 'IndexController@login');
Route::get('/cadastrar', 'IndexController@register');

Route::get('/home', 'HomeController@principal');

Route::resource('/pacientes', 'PacientesController');

Route::resource('/medicos', 'MedicosController');

Route::resource('/agendamentos', 'AgendamentosController');

//Route::resource('/agendamentos/agenda', 'AgendaController');--teste


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Agendamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agendamento extends Model
{
    //

    public function medico()
    {
        return $this->belongsTo(Medico::class, 'id_medico');
    }

    public function paciente()
    {
        return $this->belongsTo(Paciente::class, 'id_paciente');
    }
    
}

app/Http/Controllers/AgendamentosController.php
<?php

namespace App\Http\Controllers;

use App\Agendamento;
use App\Paciente;
use App\Medico;
use Illuminate\Http\Request;

class AgendamentosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agendamentos = Agendamento::all();
        return view('agendamentos.lista')->with('agendamentos', $agendamentos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $method = 'post';
        $agendamento = new Agendamento();
        $pacientes = Paciente::all();
        $medicos = Medico::all();

        return view('agendamentos.form')->with('pacientes', $pacientes)
                                        ->with('medicos', $medicos)
                                        ->with('method', $method)
                                        ->with('agendamento', $agendamento);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'descricao' => 'required|min:5',
            'datahora' => 'required',
            'paciente_id' => 'required',
            'medico_id' => 'required', 
            'legenda' => 'required',            
        ]);
        if ($validator->fails()) {
            return back()->withErrors($validator);
        } else {
            $agendamento = new Agendamento();
            $agendamento->descricao = $request->input('descricao');
            $agendamento->datahora = $request->input('datahora');
            $agendamento->id_paciente = $request->input('paciente_id');
            $agendamento->id_medico = $request->input('medico_id');
            $agendamento->legenda = $request->input('legenda');
            $agendamento->save();

            return redirect()->route('agendamentos.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $method = 'put';
        $agendamento = Agendamento::find($id);
        $pacientes = Paciente::all();
        $medicos = Medico::all();        
        return view('agendamentos.form')->with('method', $method)
                                        ->with('agendamento', $agendamento)
                                        ->with('pacientes', $pacientes)
                                        ->with('medicos', $medicos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'descricao' => 'required|min:5',
            'datahora' => 'required',
            'paciente_id' => 'required',
            'medico_id' => 'required', 
            'legenda' => 'required',           
        ]);
        if ($validator->fails()) {
            return back()->withErrors($validator);
        } else {
            $agendamento = Agendamento::find($id);
            $agendamento->descricao = $request->input('descricao');
            $agendamento->datahora = $request->input('datahora');
            $agendamento->id_paciente = $request->input('paciente_id');
            $agendamento->id_medico = $request->input('medico_id');
            $agendamento->legenda = $request->input('legenda');
            $agendamento->save();

            return redirect()->route('agendamentos.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $agendamento = Agendamento::find($id);
        
        $agendamento->delete();

        return redirect()->route('agendamentos.index');
    }
}

resources/views/agendamentos/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading painel_cab">
                    Faça o agendamento da consulta médica
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="panel-body">
                    @if($method == 'put')
                    <form action="{{ route('agendamentos.update', $agendamento->id) }}" method="post">
                        {{ csrf_field() }}                        
                        {{ method_field('PUT') }}
                    @else
                    <form action="{{ route('agendamentos.store') }}" method="post">
                        {{ csrf_field() }}
                    @endif
                        <div class="form-group">
                            <label for="descricao">Descrição</label>
                            <input id="descricao" type="text" name="descricao" class="form-control" value="{{ $agendamento->descricao }}"/>
                        </div>

                        <div class="form-group">
                            <label for="datahora">Data/Hora</label>
                            <input id="datahora" type="datetime-local" name="datahora" class="form-control" value="{{ strftime('%Y-%m-%dT%H:%M', strtotime($agendamento->datahora)) }}"/>
                        </div>                        

                        <div class="form-group">
                            <label for="paciente_id">Paciente</label>
                            <select name="paciente_id" class="form-control" id="paciente_id" value="{{ $agendamento->id_paciente }}">
                                @foreach($pacientes as $paciente)
                                    <option value="{{ $paciente->id }}" {{ $paciente->id == $agendamento->id_paciente ? 'selected="selected"' : ''}}> {{ $paciente->nome }} </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="medico_id">Médico</label>
                            <select name="medico_id" class="form-control" id="medico_id" value="{{ $agendamento->id_medico }}">
                                @foreach($medicos as $medico)
                                    <option value="{{ $medico->id }}" {{ $medico->id == $agendamento->id_medico ? 'selected="selected"' : ''}}> {{ $medico->nome }}  {{ $medico->especialidade }} </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="legenda">Legenda</label>
                            <input id="legenda" type="text" name="legenda" class="form-control" value="{{ $agendamento->legenda }}"/>
                        </div>
                        <!-- <div class="radio">
                          <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                            Compareceu
                          </label>
                        </div>
                        <div class="radio">
                          <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                            Remarcou
                          </label>
                        </div>
                        <div class="radio">
                          <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">
                            Faltou
                          </label>
                        </div>   -->                

                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a class="btn btn-default" href="{{ url('/agendamentos') }}">Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/agendamentos/lista.blade.php
@extends('layouts.app2')
@section('external_css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="css/jquery.bootpop.css" rel="stylesheet" type="text/css">
@endsection
@section('content')
<div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Agenda - Cadastros</div>

                <div class="panel-body">
                                        
                    
                    <ul class="nav nav-tabs">
                      <li role="presentation"><a href="home">Home</a></li>
                      <li role="presentation" class="active"><a href="#">Agendamentos</a></li>
                      <li role="presentation"><a href="pacientes">Pacientes</a></li>
                      <li role="presentation"><a href="medicos">Medicos</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading painel_cab">
                    Agendamentos
                    <a class="btn btn-primary pull-right" href="{{ route('agendamentos.create') }}">Novo</a>
                </div>
                <div class="panel-body">
                    @if(count($agendamentos) > 0)
                    <table id="agendamento_table" class="table table-striped table-hover" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Data/Hora</th>
                                <th>Paciente</th>
                                <th>Descrição</th>
                                <th>Médico</th>
                                <th>Especialidade</th>
                                <th>Editar</th>
                                <th>Excluir</th>
                                <th>Legenda</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($agendamentos as $agendamento)
                            <tr>
                                <td>{{ $agendamento->id }}</td>
                                <td>{{ date("d/m/Y H:i:s", strtotime($agendamento->datahora)) }}</td>
                                <td>{{ $agendamento->paciente->nome }}</td>
                                <td>{{ $agendamento->descricao }}</td>
                                
                                <td>{{ $agendamento->medico->nome }}</td>
                                <td>{{ $agendamento->medico->especialidade }}</td>
                                <td><a href="{{ route('agendamentos.edit', $agendamento->id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></a></td>
                                 <td>
                                    <form action="{{ route('agendamentos.destroy', $agendamento->id ) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-trash"></button>
                                    </form>
                                </td> 
                                    <td>{{ $agendamento->legenda }}</td>
                            <!-- <td><button class="btn btn-info demo" >Status</button></td> -->        
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @else
                        <p>Não há agendamentos cadastrados!</p>
                    @endif

                </div>
            </div>
        </div>
    </div>
</div>


</script>
 <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <p class="text-muted small mb-4 mb-lg-0">&copy; Renato de Oliveira Lucena 2018</p>
          </div>
        </div>
      </div>
    </footer>
@endsection

@section('external_js')

@if(count('agendamentos') > 0)
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#agendamento_table').DataTable( {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
                }
            } );            
        } );   
    </script> 

@endif
@endsection