routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Route::get('/', function () {
    return view('welcome');
});*/


Auth::routes();

Route::get('/', 'IndexController@index');
Route::get('/entrar', 'IndexController@login');
Route::get('/cadastrar', 'IndexController@register');

Route::get('/home', 'HomeController@principal');

Route::resource('/pacientes', 'PacientesController');

Route::resource('/medicos', 'MedicosController');

Route::resource('/agendamentos', 'AgendamentosController');

//Route::resource('/agendamentos/agenda', 'AgendaController');--teste


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Medico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medico extends Model
{
    //

    public function agendamentos()
    {
        return $this->hasMany(Agendamento::class, 'id_medico', 'id');
    }
}

app/Http/Controllers/MedicosController.php
<?php

namespace App\Http\Controllers;

use App\Medico;
use Illuminate\Http\Request;

class MedicosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $medicos = Medico::all();
        return view('medicos.lista')->with('medicos', $medicos);
    }

    // API
    public function listaMedicos(){
        $medicos = Medico::all();
        return response()->json($medicos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $method = 'post';
        $medico = new Medico();
        return view('medicos.form')->with('method', $method)
                                     ->with('medico', $medico);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'nome' => 'required|min:3',
            'crm' => 'required',
            'especialidade' => 'required',
            'telefone' => 'required',
        ]);
        if ($validator->fails()) {
            return back()->withErrors($validator);
        } else {
            $medico = new Medico();
            $medico->nome = $request->input('nome');
            $medico->crm = $request->input('crm');
            $medico->especialidade = $request->input('especialidade');
            $medico->telefone = $request->input('telefone');
            $medico->save();

            return redirect()->route('medicos.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $method = 'put';
        $medico = Medico::find($id);
        return view('medicos.form')->with('method', $method)
        ->with('medico', $medico);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'nome' => 'required|min:3',
            'crm' => 'required',
            'especialidade' => 'required',
            'telefone' => 'required',
        ]);
        if ($validator->fails()) {
            return back()->withErrors($validator);
        } else {
            $medico = Medico::find($id);
            $medico->nome = $request->input('nome');
            $medico->crm = $request->input('crm');
            $medico->especialidade = $request->input('especialidade');
            $medico->telefone = $request->input('telefone');
            $medico->save();

            return redirect()->route('medicos.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $medico = Medico::find($id);
        
        $medico->delete();
        
        return redirect()->route('medicos.index');
    }
}

resources/views/medicos/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading painel_cab">
                    Informe abaixo as informações do médico
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="panel-body">
                    @if($method == 'put')
                    <form action="{{ route('medicos.update', $medico->id) }}" method="post">
                        {{ csrf_field() }}                        
                        {{ method_field('PUT') }}
                    @else
                    <form action="{{ route('medicos.store') }}" method="post">
                        {{ csrf_field() }}
                    @endif
                        <div class="form-group">
                            <label for="nome">Nome</label>
                            <input id="nome" type="text" name="nome" class="form-control" value="{{ $medico->nome }}" required/>
                        </div>

                        <div class="form-group">
                            <label for="crm">CRM</label>
                            <input id="crm" type="text" name="crm" value="{{ $medico->crm }}" class="form-control" required/>
                        </div>

                        <div class="form-group">
                            <label for="telefone">Telefone</label>
                            <input id="telefone" type="text" name="telefone" value="{{ $medico->telefone }}" class="form-control telefone" required/>
                        </div>

                        <div class="form-group">
                            <label for="especialidade">Especialidade</label>
                            <input id="especialidade" type="text" name="especialidade" value="{{ $medico->especialidade }}" class="form-control especialidade" required/>
                        </div>

                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a class="btn btn-default" href="{{ url('/medicos') }}">Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('external_js')    
    <script src="http://digitalbush.com/wp-content/uploads/2014/10/jquery.maskedinput.js"></script>
    <script type="text/javascript">
        jQuery("input.telefone")
        .mask("(99) 9999-9999?9")
        .focusout(function (event) {  
            var target, phone, element;  
            target = (event.currentTarget) ? event.currentTarget : event.srcElement;  
            phone = target.value.replace(/\D/g, '');
            element = $(target);  
            element.unmask();  
            if(phone.length > 10) {  
                element.mask("(99) 99999-999?9");  
            } else {  
                element.mask("(99) 9999-9999?9");  
            }  
        });
    </script>    
@endsection

resources/views/medicos/lista.blade.php
@extends('layouts.app')

@section('external_css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
@endsection
@section('content')
<div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Agenda - Cadastros</div>

                <div class="panel-body">
                                        
                    
                    <ul class="nav nav-tabs">
                      <li role="presentation"><a href="home">Home</a></li>
                      <li role="presentation"><a href="agendamentos">Agendamentos</a></li>
                      <li role="presentation"><a href="pacientes">Pacientes</a></li>
                      <li role="presentation" class="active"><a href="#">Medicos</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading painel_cab">
                    Médicos
                    <a class="btn btn-primary pull-right" href="{{ route('medicos.create') }}">Novo</a>
                </div>
                <div class="panel-body">
                    @if(count($medicos) > 0)
                    <table id="medico_table" class="table table-striped table-hover" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>CRM</th>
                                <th>Telefone</th>
                                <th>especialidade</th>
                                <th>Editar</th>
                                <th>Excluir</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($medicos as $medico)
                            <tr>
                                <td>{{ $medico->id }}</td>
                                <td>{{ $medico->nome }}</td>
                                <td>{{ $medico->crm }}</td>
                                <td>{{ $medico->telefone }}</td>
                                <td>{{ $medico->especialidade }}</td>
                                <td><a href="{{ route('medicos.edit', $medico->id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></a></td>
                                 <td>
                                    <form action="{{ route('medicos.destroy', $medico->id ) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-trash"></button>
                                    </form>
                                </td> 
                                    
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @else
                        <p>Não há médicos cadastrados no momento!</p>
                    @endif

                </div>
            </div>
        </div>
    </div>
</div><br>
 <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <p class="text-muted small mb-4 mb-lg-0">&copy; Renato de Oliveira Lucena 2018</p>
          </div>
        </div>
      </div>
    </footer>
@endsection

@section('external_js')
@if(count('medicos') > 0)
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#medico_table').DataTable( {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
                }
            } );            
        } );   
    </script>    
@endif
@endsection